export interface WordPair {
  id: string;
  en: string;
  tr: string;
}

export const DEFAULT_KELIME_PATLAT_WORDS: WordPair[] = [
  { id: 'kp-1', en: 'Apple', tr: 'Elma' },
  { id: 'kp-2', en: 'Book', tr: 'Kitap' },
  { id: 'kp-3', en: 'Water', tr: 'Su' },
  { id: 'kp-4', en: 'School', tr: 'Okul' },
  { id: 'kp-5', en: 'Friend', tr: 'Arkadaş' },
  { id: 'kp-6', en: 'House', tr: 'Ev' },
  { id: 'kp-7', en: 'Sun', tr: 'Güneş' },
  { id: 'kp-8', en: 'Moon', tr: 'Ay' },
  { id: 'kp-9', en: 'Time', tr: 'Zaman' },
  { id: 'kp-10', en: 'World', tr: 'Dünya' },
  { id: 'kp-11', en: 'Dream', tr: 'Hayal' },
  { id: 'kp-12', en: 'Life', tr: 'Hayat' },
  { id: 'kp-13', en: 'Heart', tr: 'Kalp' },
  { id: 'kp-14', en: 'Smile', tr: 'Gülümseme' },
  { id: 'kp-15', en: 'Music', tr: 'Müzik' },
  { id: 'kp-16', en: 'Story', tr: 'Hikâye' },
  { id: 'kp-17', en: 'Journey', tr: 'Yolculuk' },
  { id: 'kp-18', en: 'City', tr: 'Şehir' },
  { id: 'kp-19', en: 'Tree', tr: 'Ağaç' },
  { id: 'kp-20', en: 'Bird', tr: 'Kuş' },
  { id: 'kp-21', en: 'Happy', tr: 'Mutlu' },
  { id: 'kp-22', en: 'Brave', tr: 'Cesur' },
  { id: 'kp-23', en: 'Fast', tr: 'Hızlı' },
  { id: 'kp-24', en: 'Strong', tr: 'Güçlü' },
  { id: 'kp-25', en: 'Smart', tr: 'Akıllı' },
  { id: 'kp-26', en: 'Kind', tr: 'Kibar' },
  { id: 'kp-27', en: 'Bright', tr: 'Parlak' },
  { id: 'kp-28', en: 'Silent', tr: 'Sessiz' },
  { id: 'kp-29', en: 'Easy', tr: 'Kolay' },
  { id: 'kp-30', en: 'Ready', tr: 'Hazır' },
  { id: 'kp-31', en: 'Speak', tr: 'Konuşmak' },
  { id: 'kp-32', en: 'Listen', tr: 'Dinlemek' },
  { id: 'kp-33', en: 'Learn', tr: 'Öğrenmek' },
  { id: 'kp-34', en: 'Write', tr: 'Yazmak' },
  { id: 'kp-35', en: 'Read', tr: 'Okumak' },
  { id: 'kp-36', en: 'Think', tr: 'Düşünmek' },
  { id: 'kp-37', en: 'Watch', tr: 'İzlemek' },
  { id: 'kp-38', en: 'Play', tr: 'Oynamak' },
  { id: 'kp-39', en: 'Help', tr: 'Yardım etmek' },
  { id: 'kp-40', en: 'Travel', tr: 'Seyahat etmek' },
  { id: 'kp-41', en: 'Always', tr: 'Her zaman' },
  { id: 'kp-42', en: 'Never', tr: 'Asla' },
  { id: 'kp-43', en: 'Sometimes', tr: 'Bazen' },
  { id: 'kp-44', en: 'Often', tr: 'Sık sık' },
  { id: 'kp-45', en: 'Today', tr: 'Bugün' },
  { id: 'kp-46', en: 'Tomorrow', tr: 'Yarın' },
  { id: 'kp-47', en: 'Yesterday', tr: 'Dün' },
  { id: 'kp-48', en: 'Morning', tr: 'Sabah' },
  { id: 'kp-49', en: 'Night', tr: 'Gece' },
  { id: 'kp-50', en: 'Future', tr: 'Gelecek' },
  { id: 'kp-51', en: 'Family', tr: 'Aile' },
  { id: 'kp-52', en: 'Teacher', tr: 'Öğretmen' },
  { id: 'kp-53', en: 'Student', tr: 'Öğrenci' },
  { id: 'kp-54', en: 'Question', tr: 'Soru' },
  { id: 'kp-55', en: 'Answer', tr: 'Cevap' },
  { id: 'kp-56', en: 'Power', tr: 'Güç' },
  { id: 'kp-57', en: 'Hope', tr: 'Umut' },
  { id: 'kp-58', en: 'Success', tr: 'Başarı' },
  { id: 'kp-59', en: 'Goal', tr: 'Hedef' },
  { id: 'kp-60', en: 'Star', tr: 'Yıldız' },
  { id: 'kp-61', en: 'Window', tr: 'Pencere' },
  { id: 'kp-62', en: 'Door', tr: 'Kapı' },
  { id: 'kp-63', en: 'Road', tr: 'Yol' },
  { id: 'kp-64', en: 'Sea', tr: 'Deniz' },
  { id: 'kp-65', en: 'Sky', tr: 'Gökyüzü' },
  { id: 'kp-66', en: 'Rain', tr: 'Yağmur' },
  { id: 'kp-67', en: 'Snow', tr: 'Kar' },
  { id: 'kp-68', en: 'Wind', tr: 'Rüzgar' },
  { id: 'kp-69', en: 'Fire', tr: 'Ateş' },
  { id: 'kp-70', en: 'Flower', tr: 'Çiçek' },
  { id: 'kp-71', en: 'Start', tr: 'Başlamak' },
  { id: 'kp-72', en: 'Finish', tr: 'Bitirmek' },
  { id: 'kp-73', en: 'Open', tr: 'Açmak' },
  { id: 'kp-74', en: 'Close', tr: 'Kapatmak' },
  { id: 'kp-75', en: 'Choose', tr: 'Seçmek' },
  { id: 'kp-76', en: 'Find', tr: 'Bulmak' },
  { id: 'kp-77', en: 'Win', tr: 'Kazanmak' },
  { id: 'kp-78', en: 'Fly', tr: 'Uçmak' },
  { id: 'kp-79', en: 'Remember', tr: 'Hatırlamak' },
  { id: 'kp-80', en: 'Forget', tr: 'Unutmak' },
];
